#pragma once
#include "stdafx.h"
#include <windows.h>
#include <string>
#include <iostream>

class ClasseIntegracao
{
   private:
	
	bool semTelas; 
	typedef void *(__stdcall *ptrCallBackDisplayTerminal)(char *pMensagem);
	typedef void *(__stdcall *ptrCallBackDisplayErro)(char *pMensagem);
	typedef void *(__stdcall *ptrCallBackMensagem)(char *pMensagem);
	typedef void *(__stdcall *ptrCallBackBeep)(void);
	typedef int *(__stdcall *ptrCallBackSolicitaConfirmacao)(char *pMensagem);
	typedef int *(__stdcall *ptrCallBackEntraCartao)(char *pLabel, char *pCartao);
	typedef int *(__stdcall *ptrCallBackEntraDataValidade)(char *pLabel, char *pDataValidade);
	typedef int *(__stdcall *ptrCallBackEntraData)(char *pLabel, char *pDataValidade);
	typedef int *(__stdcall *ptrCallBackEntraCodigoSeguranca)(char *pLabel, char *pEntraCodigoSeguranca,int iTamanhoMax);
	typedef int *(__stdcall *ptrCallBackSelecionaOpcao)(char *pLabel, char *pOpcoes, int *iOpcaoSelecionada);
	typedef int *(__stdcall *ptrCallBackEntraValor)(char *pLabel, char *pValor, char *pValorMinimo, char *pValorMaximo);
  typedef int *(__stdcall *ptrCallBackEntraValorEspecial)(char *pLabel, char *pValor, char* pParametros);
	typedef int *(__stdcall *ptrCallBackEntraNumero)(char *pLabel, char *pNumero, char *pNumeroMinimo, char *pNumeroMaximo,int iMininoDigitos,int iMaximoDigitos,int iDigitosExatos);
	typedef int *(__stdcall *ptrCallBackOperacaoCancelada) (void);
	typedef int *(__stdcall *ptrCallBackSetaOperacaoCancelada) (bool bCancelada);
	typedef void *(__stdcall *ptrCallBackProcessaMensagens) (void);
	typedef int *(__stdcall *ptrCallBackEntraString)(char *pLabel, char *pString, char *pTamanhoMaximo);
	typedef int *(__stdcall *ptrCallBackConsultaAVS)(char *cEndereco,char *cNumero,char *cApto,char *cBloco,char *cCEP,char *cBairro,char *cCPF);
	typedef int *(__stdcall *ptrCallBackMensagemAdicional)(char *pMensagemAdicional);
	typedef int *(__stdcall *ptrCallBackImagemAdicional)(int *pIndiceImagem);
	typedef int *(__stdcall *ptrCallBackEntraCodigoBarras) (char *Label,char *Campo);
	typedef int *(__stdcall *ptrCallBackEntraCodigoBarrasLido)(char *Label,char *Campo);
	typedef void *(__stdcall *ptrCallBackMensagemAlerta) (char *pMensagemAlerta);
	typedef void *(__stdcall *ptrCallBackPreviewComprovante) (char * cComprovante);
	typedef int *(__stdcall *ptrCallBackSelecionaPlanos)(int iCodigoRede, int iCodigoTransacao, int iTipoFinanciamento, int iMaximoParcelas, char *pValorMinimoParcela,
			int iMaxDiasPreDatado, char *pNumeroParcelas, char *pValorTransacao, char *pValorParcela, char *pValorEntrada, char *pData);
	typedef int *(__stdcall *ptrCallBackSelecionaPlanosEx)(char* sSolicitacao, char* sRetorno);

	typedef void (__stdcall *pCallBackDisplayTerminal)(char *pMensagem);
	typedef void (__stdcall *pCallBackDisplayErro)(char *pMensagem);
	typedef void (__stdcall *pCallBackMensagem)(char *pMensagem);
	typedef void (__stdcall *pCallBackBeep)(void);
	typedef int (__stdcall *pCallBackSolicitaConfirmacao)(char *pMensagem);
	typedef int (__stdcall *pCallBackEntraCartao)(char *pLabel, char *pCartao);
	typedef int (__stdcall *pCallBackEntraDataValidade)(char *pLabel, char *pDataValidade);
	typedef int (__stdcall *pCallBackEntraData)(char *pLabel, char *pDataValidade);
	typedef int (__stdcall *pCallBackEntraCodigoSeguranca)(char *pLabel, char *pEntraCodigoSeguranca,int iTamanhoMax);
	typedef int (__stdcall *pCallBackSelecionaOpcao)(char *pLabel, char *pOpcoes, int *iOpcaoSelecionada);
	typedef int (__stdcall *pCallBackEntraValor)(char *pLabel, char *pValor, char *pValorMinimo, char *pValorMaximo);
  typedef int(__stdcall *pCallBackEntraValorEspecial)(char *pLabel, char *pValor, char *pParametros);
	typedef int (__stdcall *pCallBackEntraNumero)(char *pLabel, char *pNumero, char *pNumeroMinimo, char *pNumeroMaximo,int iMininoDigitos,int iMaximoDigitos,int iDigitosExatos);
	typedef int (__stdcall *pCallBackOperacaoCancelada) (void);
	typedef int (__stdcall *pCallBackSetaOperacaoCancelada) (bool bCancelada);
	typedef void (__stdcall *pCallBackProcessaMensagens) (void);
	typedef int (__stdcall *pCallBackEntraString)(char *pLabel, char *pString, char *pTamanhoMaximo);
	typedef int (__stdcall *pCallBackConsultaAVS)(char *cEndereco,char *cNumero,char *cApto,char *cBloco,char *cCEP,char *cBairro,char *cCPF);
	typedef int (__stdcall *pCallBackMensagemAdicional)(char *pMensagemAdicional);
	typedef int (__stdcall *pCallBackImagemAdicional)(int *iIndiceImagem);
	typedef int (__stdcall *pCallBackEntraCodigoBarras) (char *Label,char *Campo);
	typedef int (__stdcall *pCallBackEntraCodigoBarrasLido)(char *Label,char *Campo);
	typedef void (__stdcall *pCallBackMensagemAlerta) (char *pMensagemAlerta);
	typedef void (__stdcall *pCallBackPreviewComprovante) (char * cComprovante);
	typedef int (__stdcall *pCallBackSelecionaPlanos)(int iCodigoRede, int iCodigoTransacao, int iTipoFinanciamento, int iMaximoParcelas, char *pValorMinimoParcela,
			int iMaxDiasPreDatado, char *pNumeroParcelas, char *pValorTransacao, char *pValorParcela, char *pValorEntrada, char *pData);
	typedef int (__stdcall *pCallBackSelecionaPlanosEx)(char* sSolicitacao, char* sRetorno);

	typedef void (__stdcall *RegPDVDisplayTerminal)(pCallBackDisplayTerminal);
	typedef void (__stdcall *RegPDVDisplayErro)(pCallBackDisplayErro);
	typedef void (__stdcall *RegPDVMensagem)(pCallBackMensagem);
	typedef void (__stdcall *RegPDVBeep)(pCallBackBeep);
	typedef void (__stdcall *RegPDVSolicitaConfirmacao)(pCallBackSolicitaConfirmacao);
	typedef void (__stdcall *RegPDVEntraCartao)(pCallBackEntraCartao);
	typedef void (__stdcall *RegPDVEntraDataValidade)(pCallBackEntraDataValidade);
	typedef void (__stdcall *RegPDVEntraData)(pCallBackEntraData);
	typedef void (__stdcall *RegPDVEntraCodigoSeguranca)(pCallBackEntraCodigoSeguranca);
	typedef void (__stdcall *RegPDVSelecionaOpcao)(pCallBackSelecionaOpcao);
	typedef void (__stdcall *RegPDVEntraValor)(pCallBackEntraValor);
  typedef void (__stdcall *RegPDVEntraValorEspecial)(pCallBackEntraValorEspecial);
	typedef void (__stdcall *RegPDVEntraNumero)(pCallBackEntraNumero);
	typedef void (__stdcall *RegPDVOperacaoCancelada)(pCallBackOperacaoCancelada);
	typedef void (__stdcall *RegPDVSetaOperacaoCancelada)(pCallBackSetaOperacaoCancelada);
	typedef void (__stdcall *RegPDVProcessaMensagens)(pCallBackProcessaMensagens);
	typedef void (__stdcall *RegPDVEntraString)(pCallBackEntraString);
	typedef void (__stdcall *RegPDVConsultaAVS)(pCallBackConsultaAVS);
	typedef void (__stdcall *RegPDVImagemAdicional)(pCallBackImagemAdicional);
	typedef void (__stdcall *RegPDVMensagemAdicional)(pCallBackMensagemAdicional);
	typedef void (__stdcall *RegPDVEntraCodigoBarras)(pCallBackEntraCodigoBarras);
	typedef void (__stdcall *RegPDVEntraCodigoBarrasLido)(pCallBackEntraCodigoBarrasLido);
	typedef void (__stdcall *RegPDVMensagemAlerta)(pCallBackMensagemAlerta);
	typedef void (__stdcall *RegPDVPreviewComprovante)(pCallBackPreviewComprovante);
	typedef void (__stdcall *RegPDVSelecionaPlanos)(pCallBackSelecionaPlanos);
	typedef void (__stdcall *RegPDVSelecionaPlanosEx)(pCallBackSelecionaPlanosEx);

	typedef int (__stdcall *FTransacaoCartaoCredito)(char* valor, char* numeroCupom, char* numeroControle);
	typedef int (__stdcall *FTransacaoCartaoDebito)(char* valor, char* numeroCupom, char* numeroControle);
	typedef void (__stdcall *FVersaoDPOS)(char *pVersao); 
	typedef int (__stdcall *FTransacaoCartaoFrota)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	typedef int (__stdcall *FConfirmaCartaoFrota)(char *pNumeroControle);
	typedef int (__stdcall *FTransacaoCartaoFrotaCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pTipoProduto,
			char *pCodigoVeiculo, char *pCodigoCondutor, char *pKilometragem, char *pDadosServicos,  char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FImprimeCupomTEF)(char *pPathArquivoCupomTEF, char *pMensagemOperador); 
	typedef int (__stdcall *FTransacaoCartaoParceleMais)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle,char *pCodigoTabela); 
	typedef int (__stdcall *FTransacaoCartaoParceleMaisCompleta)(char *pValorTransacao, char *pNumeroCupom,char *pNumeroControle,char *pCodigoTabela,
			char *pNumeroParcelas, char *pValorParcela,char *pVencimentoPrimeiraParcela, char *pPermiteAlteracao); 
	typedef int (__stdcall *FTransacaoCartaoVoucher)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCheque)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pQuantidadeCheques, char *pPeriodicidadeCheques,
			char *pDataPrimeiroCheque, char *pCarenciaPrimeiroCheque); 
	typedef int (__stdcall *FTransacaoCelular)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCancelamentoCelular)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCancelamentoGarantiaCheque)(char *pValorTransacao, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCancelamentoPagamento)(char *pNumeroControle); 
	typedef int (__stdcall *FEstornoPreAutorizacaoRedecard)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoConfirmacaoPreAutorizacao)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCancelamentoPagamentoCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FConfirmaCartaoCredito)(char *pNumeroControle); 
	typedef int (__stdcall *FConfirmaCartaoDebito)(char *pNumeroControle); 
	typedef int (__stdcall *FConfirmaCartaoVoucher)(char *pNumeroControle); 
	typedef int (__stdcall *FConfirmaDebitoBeneficiario)(char *pNumeroControle); 
	typedef int (__stdcall *FConfirmaCartao)(char *pNumeroControle); 
	typedef int (__stdcall *FDesfazCartao)(char *pNumeroControle); 
	typedef int (__stdcall *FFinalizaTransacao)(); 
	typedef int (__stdcall *FTransacaoConsultaParcelas)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoConsultaParcelasCredito)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoConsultaParcelasCelular)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoPreAutorizacao)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoPreAutorizacaoCartaoCredito)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoPreAutorizacaoCartaoFrota)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoFuncaoEspecial)(); 
	typedef int (__stdcall *FTransacaoResumoVendas)(char *pNumeroControle); 
	typedef void (__stdcall *FDadosUltimaTransacao)(char *pDadosUltimaTransacao); 
	typedef void (__stdcall *FObtemCodigoRetorno)(int iCodigoRetorno, char *pCodigoRetorno);
	typedef void (__stdcall *FObtemLogUltimaTransacao)(char *oLogUltimaTransacao); 
	typedef void (__stdcall *FObtemLogUltimaTransacaoTeleMarketing)(char *pNumeroPDV, char *oLogUltimaTransacao); 
	typedef void (__stdcall *FObtemLogUltimaTransacaoTeleMarketingMultiLoja)(char *cNumeroEmpresa, char *cNumeroLoja, char *pNumeroPDV, char *oLogUltimaTransacao); 
	typedef void (__stdcall *FObtemComprovanteTransacao)(char *pNumeroControle, char *pComprovante, char *pComprovanteReduzido); 
	typedef void (__stdcall *FDadosUltimaTransacaoDiscada)(char *oDadosUltimaTransacaoDiscada); 
	typedef void (__stdcall *FDadosUltimaTransacaoCB)(char *pLogTitulo); 
	typedef int (__stdcall *FTransacaoCartaoCreditoCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pTipoOperacao, char *pNumeroParcelas,
			char *pValorParcela, char *pValorTaxaServico, char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FTransacaoCartaoDebitoCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pTipoOperacao, char *pNumeroParcelas,
			char *pSequenciaParcela, char *pDataDebito, char *pValorParcela, char *pValorTaxaServico, char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FTransacaoCartaoVoucherCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pReservado); 
	typedef int (__stdcall *FTransacaoChequeCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pQuantidadeCheques, char *pPeriodicidadeCheques,
			char *pDataPrimeiroCheque, char *pCarenciaPrimeiroCheque, char *pTipoDocumento, char *pNumeroDocumento, char *pQuantidadeChequesEx, char *pSequenciaCheque,
			char *pCamaraCompensacao, char *pNumeroBanco, char *pNumeroAgencia, char *pNumeroContaCorrente, char *pNumeroCheque, char *pDataDeposito,
			char *pValorCheque, char *pDataNascimentoCliente, char *pTelefoneCliente, char *pCMC7, char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FTransacaoCartaoPrivateLabelCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pTipoOperacao,
			char *pNumeroParcelas, char *pValorEntrada, char *pValorTaxaServico, char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FTransacaoSimulacaoPrivateLabel)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoConsultaPrivateLabel)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoPagamentoPrivateLabel)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoDebitoBeneficiario)(char *pValorTransacao, char *pTipoBeneficio, char *pNumeroBeneficio, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FInfAdicionaisCartaoDebito)(char *pDadosParcelas); 
	typedef int (__stdcall *FObtemInfTransacaoDebitoParcelado)(char *pDadosParcelas); 
	typedef int (__stdcall *FConsultaParametrosCB)(char *pParametros); 
	typedef int (__stdcall *FConsultaPagamentoCB)(char *pTipoConta, char *pCodigoBarrasDigitado, char *pCodigoBarrasLido, char *pValorTitulo, char *pValorDesconto, char *pValorAcrescimo, char *pDataVencimento, char *pFormaPagamento, char *pTrilhaCartao, char *pTipoSenha, char *pSenha, char *pNSUCartao, char *pTipoCMC7, char *pCMC7, char *pNumeroControle, char *pMensagemTEF, char *pImprimeComprovante, char *pParametros, char *pParametros2); 
	typedef int (__stdcall *FTransacaoPagamentoCB)(char *pTipoConta, char *pCodigoBarrasDigitado, char *pCodigoBarrasLido, char *pValorTitulo, char *pValorDesconto, char *pValorAcrescimo, char *pDataVencimento, char *pFormaPagamento, char *pTrilhaCartao, char *pTipoSenha, char *pSenha, char *pNSUCartao, char *pTipoCMC7, char *pCMC7, char *pParametros2, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCancelamentoCB)(char *pTipoConta, char *pCodigoBarrasDigitado, char *pCodigoBarrasLido, char *pValorTitulo, char *pNSUCartao, char *pNumeroControle); 
	typedef int (__stdcall *FInicializaSessaoCB)(char *pNumeroControle); 
	typedef int (__stdcall *FFinalizaSessaoCB)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoResumoRecebimentosCB)(char *pTipoRecebimento, char *pNumeroControle); 
	typedef int (__stdcall *FUltimaMensagemTEF)(char *pMensagem); 
	typedef int (__stdcall *FTransacaoReimpressaoCupom)(); 
	typedef int (__stdcall *FConfiguraDPOS)(); 
	typedef int (__stdcall *FInicializaDPOS)(); 
	typedef int (__stdcall *FFinalizaDPOS)(); 
	typedef int (__stdcall *FTransacaoFechamento)(char *pDataMovimento, char *pQuantidadeVendas, char *pValorTotalVendas, char *pQuantidadeVendasCanceladas, char *pValorTotalVendasCanceladas, char *pReservado, char *pNumeroControle, char *pMensagemOperador); 
	typedef int (__stdcall *FTransacaoFechamentoPOS)(char *pTipoRelatorio, char *pParametrosRelatorio, char *pReservado, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoAtivacaoPOS)(char *pCNPJ, char *pNumeroSerie, char *pCodAtivacao, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoInicializacaoAreaPOS)(char *pCNPJ, char *pNumeroSerie, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoLojaPOS)(char *pCNPJ, char *pNumeroSerie, char *pCodigoEmpresa, char *pCodigoLoja, char *pCodigoPDV, char *pNumeroControle); 
	typedef void (__stdcall *FObtemUltimoErro)(char *pErro); 
	typedef void (__stdcall *FDadosUltimaTransacaoNaoAprovada)(char *pDadosTransacaoNaoAprovada); 
	typedef int (__stdcall *FTransacaoColeta)(int nTipoCartao, char *pValorTransacao, char *pTrilha1, char *pTrilha2, char *pTrilha3, char *pParametros); 
	typedef int (__stdcall *FTransacaoColetaCartao)(int nTipoCartao, char *pTrilha1, char *pTrilha2, char *pTrilha3); 
	typedef int (__stdcall *FTransacaoColetaSenha)(char *pValor, char *pSenha); 
	typedef int (__stdcall *FTransacaoColetaSenhaCartao)(int nTipoCartao, char *pValor, char *pTrilha2, char *pReservado, char *pSenha); 
	typedef int (__stdcall *FColetaPlanoPagamento)(char *pDescricaoFormaPagamento, char *pValorTransacao, char *pNumeroCupom, char *pTipoFormaPagamento, char *pNumeroControle, char *pNumeroParcelas, char *pValorAcrescimo, char *pValorEntrada, char *pValorTotal, char *pCodigoPlano, char *pPlano, char *pParcelas); 
	typedef int (__stdcall *FTransacaoAdministrativaTEFDiscado)(char *pNumeroControle); 
	typedef int (__stdcall *FSelecionaTEF)(); 
	typedef int (__stdcall *FExportaPlanos)(); 
	typedef int (__stdcall *FTransacaoQuantidade)(char *pValorTransacao, char *pValorTransacaoMaximo, char *pNumeroCupom); 
	typedef int (__stdcall *FTransacaoValor)(char *pValorTransacao, char *pValorTransacaoMaximo, char *pNumeroCupom); 
	typedef int (__stdcall *FTransacaoCartaoCreditoConfirmada)(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroCartao, char *pDataVencimento, char *pCVV2, char *pTipoOperacao, char *pNumeroParcelas, char *pValorTaxaServico, char *pMensagemTEF, char *pReservado); 
	typedef int (__stdcall *FTransacaoCancelamentoConfirmada)(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTransacao, char *pNumeroControle, char *pNumeroCartao, char *pMensagemTEF, char *pReservado); 
	typedef int (__stdcall *FPreAutorizacaoCreditoConfirmada)(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroCartao, char *pDataVencimento, char *pCVV2, char *pValorTaxaServico, char *pNumeroAutorizacao, char *pMensagemTEF, char *pReservado); 
	typedef int (__stdcall *FConfPreAutorizacaoCreditoConfirmada)(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pDataPreAutor, char *pNumeroCartao, char *pDataVencimento, char *pCVV2, char *pTipoOperacao, char *pNumeroParcelas, char *pMensagemTEF, char *pReservado); 
	typedef int (__stdcall *FTransacaoManualPOS)(char *pValorTransacao); 
	typedef int (__stdcall *FTransacaoManualPOSCompleta )(char *pValorTransacao, char *pCodigoEstabelecimento, char *pData, char *pHora, char *pNumeroAutorizadora, char *pNumeroCartao, char *pTipoOperacao, char *pNumeroParcelas, char *pDataPreDatado, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCartaoFidelidade)(char *pValorTransacao, char *pNumeroCupom, char *pCompraPontos, char *pQuantidadeItensTaxaVariavel, char *pItensTaxaVariavel, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoDebitoFidelidade)(char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FConfirmaCartaoFidelidade)(char *pNumeroControle); 
	typedef int (__stdcall *FExtratoCartaoAutorizadorDirecao)(char *pNumeroCartao, char *pNumeroControle); 
	typedef int (__stdcall *FRecebimentoAutorizadorDirecao)(char *pValorTransacao, char *pNumeroCartao, char *pNumeroControle); 
	typedef int (__stdcall *FEstornoRecebimentoAutorizadorDirecao)(char *pValorTransacao, char *pNumeroCartao, char *pNumeroControle); 
	typedef int (__stdcall *FRecebimentoCarneAutorizadorDirecao)(char *pValorTransacao, char *pNumeroCartao, char *pDataVencimento, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoPagamentoConvenio)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FConfirmaConvenio)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoSaqueRedecard)(char *pValorTransacao, char *pNumeroCupomFiscal, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoSaque)(char *pValorTransacao, char *pNumeroCupomFiscal, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCDC1MIN)(char *pValorTransacao, char *pNumeroCupomFiscal, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoSIMparcelado)(char *pValorTransacao, char *pNumeroCupomFiscal, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCartaoCreditoIATA)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCartaoCreditoIATAConfirmada)(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroCartao, char *pDataVencimento, char *pCVV2, char *pTipoOperacao, char *pNumeroParcelas, char *pValorTaxaServico,char *pValorEntrada, char *pMensagemTEF, char *pReservado); 
	typedef int (__stdcall *FTransacaoCartaoPrivateLabel)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef void (__stdcall *FBeepErro)(); 
	typedef int (__stdcall *FTransacaoConsultaSaldo)(char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoConsultaSaldoCelular)(char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoConsultaSaldoCompleta)(char *pNumeroCupom, char *pNumeroControle, char *pTipoCartao, char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FColetaCartaoDebito)(char *pValorTransacao, char *pNumeroCupom, char *pParametrosTEF, char *pMensagemOperador); 
	typedef int (__stdcall *FConsisteDadosCartaoDebito)(char *pUltimosDigitos, char *pCodigoSeguranca, char *pMensagemOperador); 
	typedef int (__stdcall *FColetaSenhaCartaoDebito)(char *pNumeroControle, char *pMensagemOperador); 
	typedef int (__stdcall *FConsultaParametrosPBM)(char *pNumeroCupom, char *pQuantidadeRedes, char *pDadosRedes, char *pMensagemOperador); 
	typedef int (__stdcall *FConsultaProdutosPBM)(char *pNumeroCupom, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pAutorizacao, char *pDadosCRM, char *pTipoVenda, char *pValorTotalMedicamentos, char *pValorVista, char *pValorCartao, char *pCodigoCredenciado, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pReservado, char *pNumeroControle, char *pMensagemOperador); 
	typedef int (__stdcall *FTransacaoVendaPBM)(char *pValorTotalMedicamentos, char *pNumeroCupom, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pAutorizacao, char *pNSUConsulta, char *pDadosCRM, char *pTipoVenda, char *pValorVista, char *pValorCartao, char *pCodigoCredenciado, char *pRegraNegocio, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pReservado, char *pNumeroControle, char *pNumeroControleRede, char *pMensagemOperador); 
	typedef int (__stdcall *FConfirmaVendaPBM)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoReimpressaoVendaPBM)(); 
	typedef int (__stdcall *FTransacaoCancelamentoVendaPBM)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCancelamentoPreAutorizacaoPBM)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoElegibilidadePBM)(char *pNumeroCupom, char *pRedePBM, char *pMatricula, char *pDadosElegibilidade, char *pNumeroControle, char *pNumeroControleRede, char *pNomeCliente, char *pNomeMedico, char *pInformaDependente, char *pListaDependentes, char *pReservado, char *pMensagemOperador);
	typedef int (__stdcall *FTransacaoPreAutorizacaoPBM)(char *pNumeroCupom, char *pRedePBM, char *pAutorizacaoElegibilidade, char *pDadosFarmaceutico, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pNumeroControle, char *pNumeroControleRede, char *pReservado, char *pMensagemOperador);
	typedef int (__stdcall *FTransacaoCancelamentoPreAutorizacaoPBM_TeleMarketing)(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pMatricula, char *pReservado, char *pNumeroControle, char *pMensagemOperador);
	typedef int (__stdcall *FTransacaoElegibilidadePBM_TeleMarketing)(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroCupom, char *pRedePBM, char *pMatricula, char *pDadosElegibilidade, char *pNumeroControle, char *pNumeroControleRede, char *pNomeCliente, char *pNomeMedico, char *pInformaDependente, char *pListaDependentes, char *pReservado, char *pMensagemOperador);
	typedef int (__stdcall *FTransacaoPreAutorizacaoPBM_TeleMarketing)(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroCupom, char *pRedePBM, char *pAutorizacaoElegibilidade, char *pDadosFarmaceutico, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pNumeroControle, char *pNumeroControleRede, char *pReservado, char *pMensagemOperador);
	typedef int (__stdcall *FConsultaParametrosPBM_TeleMarketing)(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroCupom, char *pQuantidadeRedes, char *pDadosRedes, char *pMensagemOperador); 
	typedef int (__stdcall *FConsultaProdutosPBM_TeleMarketing)(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroCupom, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pAutorizacao, char *pDadosCRM, char *pTipoVenda, char *pValorTotalMedicamentos, char *pValorVista, char *pValorCartao, char *pCodigoCredenciado, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pReservado, char *pNumeroControle, char *pMensagemOperador); 
	typedef int (__stdcall *FTransacaoVendaPBM_TeleMarketing)(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTotalMedicamentos, char *pNumeroCupom, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pAutorizacao, char *pNSUConsulta, char *pDadosCRM, char *pTipoVenda, char *pValorVista, char *pValorCartao, char *pCodigoCredenciado, char *pRegraNegocio, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pReservado, char *pNumeroControle, char *pNumeroControleRede, char *pMensagemOperador); 
	typedef int (__stdcall *FTransacaoCancelamentoVendaPBM_TeleMarketing)(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pReservado, char *pNumeroControle, char *pMensagemOperador); 
	typedef int (__stdcall *FTransacaoAberturaVendaPBM_TeleMarketing)(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pReservado, char *pPedirDadosComplementares, char *pDadosComplementares, char *pInfoDadosComplementares, char *pMensagemOperador); 
	typedef int (__stdcall *FTransacaoVendaProdutoPBM_TeleMarketing)(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pMedicamento, char *pReservado, char *pPedirDadosComplementares, char *pDadosComplementares,  char *pInfoDadosComplementares, char *pMensagemOperador); 
	typedef int (__stdcall *FTransacaoFechamentoVendaPBM_TeleMarketing)(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pConfirmacao, char *pReservado, char *pAutorizacao, char *pNumeroControle, char *pMensagemOperador); 
	typedef void (__stdcall *FInformaDadosMedicamentos)(char *pIndicativoReceita, char *pRegistroProfissional, char *pListaMedicamentos); 
	typedef int (__stdcall *FTransacaoSaqueSaldo)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoSaqueExtrato)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoConsultaAVS)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoConsultaAVSConfirmada)(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroCupom, char *pNumeroControle, char *pNumeroCartao, char *pDataVencimento, char *pCVV2, char *pEndereco, char *pNumero, char *pApto, char *pBloco, char *pCEP, char *pBairro, char *pCPF, char *pMensagemTEF, char *pReservado); 
	typedef int (__stdcall *FTransacaoPagamentoContasVisanet)(char* pTipoConta, char *pCodigoBarras, char *pFormaPagamento, char *pTrilhaCartao, char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoEspecial)(int iCodigoTransacao, char *pDados); 
	typedef int (__stdcall *FConsultaValoresPrePago)(char *pNumeroControle, char *pMensagemOperador); 
	typedef int (__stdcall *FTransacaoRecargaCelular)(char *pCodigoArea, char *pNumeroTelefone, char *pNumeroControle); 
	typedef int (__stdcall *FConsultaParametrosTeledata)(char *pDadosTeledata, char *pMensagemOperador); 
	typedef int (__stdcall *FConsultaChequesGarantidos)(char *pTipoDocumento, char *pNumeroDocumento, char *pDataInicialConsulta, char *pDataFinalConsulta, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoSaqueCompleta)(char *pValorTransacao, char *pNumeroCupomFiscal, char *pNumeroControle, char *pTipoTransacao, char *pPlanoPagamento, char *pNumeroParcelas, char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FTransacaoCartaoCompraSaque)(char *pValorCompra,char *pValorSaque, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCartaoCompraSaqueCompleta)(char *pValorCompra,char *pValorSaque, char *pNumeroCupom,char *pNumeroControle,char *pPermiteAlteracao); 
	typedef int (__stdcall *FTesteRedeAtiva)(char *pNumeroEmpresa, char *pNumeroLoja, char *pNumeroPDV, char *pCodigoRede, char *pStatusRede, char *pMensagemOperador); 
	typedef int (__stdcall *FTransacaoCadastraSenha)(char *pNumeroControle); 
	typedef void (__stdcall *FConfiguraFluxoExternoDTEF5)(); 
	typedef int (__stdcall *FTrataDesfazimento)(int iTratar); 
	typedef int (__stdcall *FConsultaTransacao)(char *pNumeroEmpresa, char *pNumeroLoja, char *pNumeroPDV, char *pSolicitacao, char *pResposta, char *pMensagemErro); 
	typedef int (__stdcall *FTransacaoeValeGas)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroValeGas); 
	typedef int (__stdcall *FTransacaoConsultaeValeGas)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroValeGas, char *pDadosRetorno); 
	typedef int (__stdcall *FTransacaoCancelamentoPadrao)(char *pNumeroControle); 
	typedef int (__stdcall *FConfiguraModoTeleMarketing)(int iModo); 
	typedef int (__stdcall *FConfirmaCartaoTeleMarketing)(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroControle, char *pMensagemTEF, char *pReservado); 
	typedef int (__stdcall *FDesfazCartaoTeleMarketing)(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroControle, char *pMensagemTEF, char *pReservado); 
	typedef int (__stdcall *FTransacaoEstatistica)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoInjecaoChaves)(char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoTrocoSurpresa)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pMensagemTEF, char *pReservado); 
	typedef int (__stdcall *FIdentificacaoAutomacaoComercial)(char *pNomeAutomacao, char *pVersaoAutomacao, char *pReservado); 
	typedef int (__stdcall *FConsultaTabelasValeGas)(char *pNumeroControle, char *pMensagemOperador); 
	typedef int (__stdcall *FDefineBandeiraTransacao)(char *pCodigoBandeira); 
	typedef int (__stdcall *FDefineRedeTransacao)(char *pCodigoRede); 
	typedef int (__stdcall *FConverteCodigoRede)(char *pCodigoRede, char *pCodigoRedeDTEF5, char *pCodigoRedeDTEF8); 
	typedef int (__stdcall *FTransacaoAbreLote)(char *pNumeroCupom, char *pNumeroControle, char *pMensagemTEF, char *pReservado); 
	typedef int (__stdcall *FTransacaoFechaLote)(char *pNumeroCupom, char *pNumeroControle, char *pMensagemTEF, char *pReservado); 
	typedef void (__stdcall *FConfiguraEmpresaLojaPDV)(char *pNumeroEmpresa, char *pNumeroLoja, char *pNumeroPDV); 
	typedef int (__stdcall *FTransacaoResgatePremio)(char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoVendaPOS)(char *pCNPJ, char *pNumeroSerie, char *pCodigoFrentista, char *pCPFCNPJ, char *pPagamentoTEF, char *pCartaoProprio, char *pValor, char *pTelefoneCliente, char *pCodigoOrigem, char *pSaldoPontos, char *pCodigoPesquisa, char *pReservado, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoEstornoVendaPOS)(char *pCNPJ, char *pNumeroSerie, char *pCodigoFrentista, char *pCPFCNPJ, char *pDataEstorno, char *pNSUEstorno, char *pAutorizacaoEstorno, char *pSaldoPontos, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoResgatePontosPOS)(char *pCNPJ, char *pNumeroSerie, char *pCodigoFrentista, char *pCPFCNPJ, char *pQuantidadeProdutos, char *pListaProdutos, char *pSaldoPontos, char *pReservado, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoConsultaPontosPOS)(char *pCNPJ, char *pNumeroSerie, char *pCodigoFrentista, char *pCPFCNPJ, char *pSaldoPontos, char *pReservado, char *pNumeroControle); 
	typedef int (__stdcall *FAtualizacaoFrentistasPOS)(char *pCNPJ, char *pNumeroSerie, char *pNumeroFrentistas, char *pListaFrentistas, char *pReservado, char *pNumeroControle); 
	typedef int (__stdcall *FBuscaTabelaDTEF)(int iTipoTabela, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoContratacao)(char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoPrimeiraCompra)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoCadastro)(char *pCNPJ, char *pNumeroSerie, char *pCodigoFrentista, char *pCPFCNPJ, char *pTelefoneCliente, char *pReservado, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoDesativacaoPOS)(char *pCNPJ, char *pNumeroSerie, char *pNumeroSerieDesativacao, char *pFrentista, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoConsultaPOSAtivos)(char *pCNPJ, char *pNumeroSerie, char *pNumeroPOSAtivos, char *pListaPOSAtivos, char *pNumeroControle); 
	typedef int (__stdcall *FProcuraPinPad)(char *pDados); 
	typedef int (__stdcall *FApagaTabelasPinPad)(char *pDados); 
	typedef int (__stdcall *FTransacaoFuncoesAdministrativas)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pReservado); 
	typedef int (__stdcall *FTransacaoQuitacaoCartaFrete)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoQuitacaoCartaFreteCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle,char *pNumeroCartaFrete,char *pQuantidadeChegada, char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FTransacaoCartaoCrediario)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoSimulacaoCrediario)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoPagamentoPrivateLabelCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pIndicadorDigitacao, char *pCodigoBarras, char *pNumeroCartao, char *pCodigoRede, char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FTransacaoCargaCartao)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoRecargaCartao)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FCadastraPDV)(); 
	typedef int (__stdcall *FCadastraPDVTelemarketing)(char *pNumeroEmpresa, char *pNumeroLoja, char *pNumeroPDV, char *pMensagemTEF); 
	typedef int (__stdcall *FTransacaoCartaoCrediarioCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroParcelas, char *pDataParcela1, char *pValorParcela1, char *pValorEntrada, char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FTransacaoConsultaPlanos)(char *pValorTransacao, char *pNumeroControle, char *pReservado, char *pPlanos); 
	typedef int (__stdcall *FConsultaCadastroPDV)(char *pMensagem); 
	typedef int (__stdcall *FConsultaCadastroPDVTelemarketing)(char *pNumeroEmpresa, char *pNumeroLoja, char *pNumeroPDV, char *pMensagemTEF); 
	typedef int (__stdcall *FTransacaoSimulacaoSaque)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoBloqueioCartao)(char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoDesbloqueioCartao)(char *pNumeroCupom, char *pNumeroControle); 
	typedef int (__stdcall *FTransacaoConsultaCadastroCPFCompleta)(char *pValorTransacao,char *pNumeroCupom, char *pNumeroControle,char *pTipoOperacao,char *pDocEmissor,char *pPermiteAlteracao,char *pReservado); 
	typedef int (__stdcall *FTransacaoDepositoCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle,char *pTipoOperacao,char *pDocEmissor,char *pDocDestinatario,char *pPermiteAlteracao,char *pReservado); 
	typedef int (__stdcall *FTransacaoSaqueDomesticoCompleta)(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle,char *pTipoOperacao,char *pCodigoPIN,char *pDocDestinatario,char *pPermiteAlteracao, char *pReservado); 
	typedef int (__stdcall *FTransacaoAlteraSenhaUsuarioDTEF)(char *pNumeroCupom, char *pNumeroControle); 

	typedef int (__stdcall *FDefineParametroTransacao)(int iCodigoParametro, char *pValorParametro, int iTamanhoParametro); 
	typedef int(__stdcall * FDefineParametroConfirmacao)(int iCodigoParametro,char *pValorParamtero,char *pTamanhoParametro);

public:

	int TransacaoCartaoCredito(char* valor, char* numeroCupom, char* numeroControle);
	void carregaDll(void);
	void VersaoDPOS(char *pVersao);
	int TransacaoCartaoFrota(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int ConfirmaCartaoFrota(char *pNumeroControle);
	int TransacaoCartaoFrotaCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pTipoProduto, char *pCodigoVeiculo, char *pCodigoCondutor, char *pKilometragem, char *pDadosServicos,  char *pPermiteAlteracao, char *pReservado);
	int ImprimeCupomTEF(char *pPathArquivoCupomTEF, char *pMensagemOperador);
	int TransacaoCartaoDebito(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoCartaoParceleMais(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle,char *pCodigoTabela);
	int TransacaoCartaoParceleMaisCompleta(char *pValorTransacao, char *pNumeroCupom,char *pNumeroControle,char *pCodigoTabela,char *pNumeroParcelas, char *pValorParcela,char *pVencimentoPrimeiraParcela, char *pPermiteAlteracao);
	int TransacaoCartaoVoucher(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoCheque(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pQuantidadeCheques, char *pPeriodicidadeCheques, char *pDataPrimeiroCheque, char *pCarenciaPrimeiroCheque);
	int TransacaoCelular(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoCancelamentoCelular(char *pNumeroControle);
	int TransacaoCancelamentoGarantiaCheque(char *pValorTransacao, char *pNumeroControle);
	int TransacaoCancelamentoPagamento(char *pNumeroControle);
	int EstornoPreAutorizacaoRedecard(char *pNumeroControle);
	int TransacaoConfirmacaoPreAutorizacao(char *pNumeroControle);
	int TransacaoCancelamentoPagamentoCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pPermiteAlteracao, char *pReservado);
	int ConfirmaCartaoCredito(char *pNumeroControle);
	int ConfirmaCartaoDebito(char *pNumeroControle);
	int ConfirmaCartaoVoucher(char *pNumeroControle);
	int ConfirmaDebitoBeneficiario(char *pNumeroControle);
	int ConfirmaCartao(char *pNumeroControle);
	int DesfazCartao(char *pNumeroControle);
	int FinalizaTransacao();
	int TransacaoConsultaParcelas(char *pNumeroControle);
	int TransacaoConsultaParcelasCredito(char *pNumeroControle);
	int TransacaoConsultaParcelasCelular(char *pNumeroControle);
	int TransacaoPreAutorizacao(char *pNumeroControle);
	int TransacaoPreAutorizacaoCartaoCredito(char *pNumeroControle);
	int TransacaoPreAutorizacaoCartaoFrota(char *pNumeroControle);
	int TransacaoFuncaoEspecial();
	int TransacaoResumoVendas(char *pNumeroControle);
	void DadosUltimaTransacao(char *pDadosUltimaTransacao);
	void ObtemCodigoRetorno(int iCodigoRetorno, char *pCodigoRetorno);;
	void ObtemLogUltimaTransacao(char *oLogUltimaTransacao);
	void ObtemLogUltimaTransacaoTeleMarketing(char *pNumeroPDV, char *oLogUltimaTransacao);
	void ObtemLogUltimaTransacaoTeleMarketingMultiLoja(char *cNumeroEmpresa, char *cNumeroLoja, char *pNumeroPDV, char *oLogUltimaTransacao);
	void ObtemComprovanteTransacao(char *pNumeroControle, char *pComprovante, char *pComprovanteReduzido);
	void DadosUltimaTransacaoDiscada(char *oDadosUltimaTransacaoDiscada);
	void DadosUltimaTransacaoCB(char *pLogTitulo);
	int TransacaoCartaoCreditoCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pTipoOperacao, char *pNumeroParcelas, char *pValorParcela, char *pValorTaxaServico, char *pPermiteAlteracao, char *pReservado);
	int TransacaoCartaoDebitoCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pTipoOperacao, char *pNumeroParcelas, char *pSequenciaParcela, char *pDataDebito, char *pValorParcela, char *pValorTaxaServico, char *pPermiteAlteracao, char *pReservado);
	int TransacaoCartaoVoucherCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pReservado);
	int TransacaoChequeCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pQuantidadeCheques, char *pPeriodicidadeCheques, char *pDataPrimeiroCheque, char *pCarenciaPrimeiroCheque, char *pTipoDocumento, char *pNumeroDocumento, char *pQuantidadeChequesEx, char *pSequenciaCheque, char *pCamaraCompensacao, char *pNumeroBanco, char *pNumeroAgencia, char *pNumeroContaCorrente, char *pNumeroCheque, char *pDataDeposito, char *pValorCheque, char *pDataNascimentoCliente, char *pTelefoneCliente, char *pCMC7, char *pPermiteAlteracao, char *pReservado);
	int TransacaoCartaoPrivateLabelCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pTipoOperacao, char *pNumeroParcelas, char *pValorEntrada, char *pValorTaxaServico, char *pPermiteAlteracao, char *pReservado);
	int TransacaoSimulacaoPrivateLabel(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoConsultaPrivateLabel(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoPagamentoPrivateLabel(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoDebitoBeneficiario(char *pValorTransacao, char *pTipoBeneficio, char *pNumeroBeneficio, char *pNumeroCupom, char *pNumeroControle);
	void InfAdicionaisCartaoDebito(char *pDadosParcelas);
	void ObtemInfTransacaoDebitoParcelado(char *pDadosParcelas);
	int ConsultaParametrosCB(char *pParametros);
	int ConsultaPagamentoCB(char *pTipoConta, char *pCodigoBarrasDigitado, char *pCodigoBarrasLido, char *pValorTitulo, char *pValorDesconto, char *pValorAcrescimo, char *pDataVencimento, char *pFormaPagamento, char *pTrilhaCartao, char *pTipoSenha, char *pSenha, char *pNSUCartao, char *pTipoCMC7, char *pCMC7, char *pNumeroControle, char *pMensagemTEF, char *pImprimeComprovante, char *pParametros, char *pParametros2);
	int TransacaoPagamentoCB(char *pTipoConta, char *pCodigoBarrasDigitado, char *pCodigoBarrasLido, char *pValorTitulo, char *pValorDesconto, char *pValorAcrescimo, char *pDataVencimento, char *pFormaPagamento, char *pTrilhaCartao, char *pTipoSenha, char *pSenha, char *pNSUCartao, char *pTipoCMC7, char *pCMC7, char *pParametros2, char *pNumeroControle);
	int TransacaoCancelamentoCB(char *pTipoConta, char *pCodigoBarrasDigitado, char *pCodigoBarrasLido, char *pValorTitulo, char *pNSUCartao, char *pNumeroControle);
	int InicializaSessaoCB(char *pNumeroControle);
	int FinalizaSessaoCB(char *pNumeroControle);
	int TransacaoResumoRecebimentosCB(char *pTipoRecebimento, char *pNumeroControle);
	int UltimaMensagemTEF(char *pMensagem);
	int TransacaoReimpressaoCupom();
	void ConfiguraDPOS();
	int InicializaDPOS();
	int FinalizaDPOS();
	int TransacaoFechamento(char *pDataMovimento, char *pQuantidadeVendas, char *pValorTotalVendas, char *pQuantidadeVendasCanceladas, char *pValorTotalVendasCanceladas, char *pReservado, char *pNumeroControle, char *pMensagemOperador);
	int TransacaoFechamentoPOS(char *pTipoRelatorio, char *pParametrosRelatorio, char *pReservado, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoAtivacaoPOS(char *pCNPJ, char *pNumeroSerie, char *pCodAtivacao, char *pNumeroControle);
	int TransacaoInicializacaoAreaPOS(char *pCNPJ, char *pNumeroSerie, char *pNumeroControle);
	int TransacaoLojaPOS(char *pCNPJ, char *pNumeroSerie, char *pCodigoEmpresa, char *pCodigoLoja, char *pCodigoPDV, char *pNumeroControle);
	void ObtemUltimoErro(char *pErro);
	void DadosUltimaTransacaoNaoAprovada(char *pDadosTransacaoNaoAprovada);
	int TransacaoColeta(int nTipoCartao, char *pValorTransacao, char *pTrilha1, char *pTrilha2, char *pTrilha3, char *pParametros);
	int TransacaoColetaCartao(int nTipoCartao, char *pTrilha1, char *pTrilha2, char *pTrilha3);
	int TransacaoColetaSenha(char *pValor, char *pSenha);
	int TransacaoColetaSenhaCartao(int nTipoCartao, char *pValor, char *pTrilha2, char *pReservado, char *pSenha);
	int ColetaPlanoPagamento(char *pDescricaoFormaPagamento, char *pValorTransacao, char *pNumeroCupom, char *pTipoFormaPagamento, char *pNumeroControle, char *pNumeroParcelas, char *pValorAcrescimo, char *pValorEntrada, char *pValorTotal, char *pCodigoPlano, char *pPlano, char *pParcelas);
	int TransacaoAdministrativaTEFDiscado(char *pNumeroControle);
	void SelecionaTEF();
	void ExportaPlanos();
	int TransacaoQuantidade(char *pValorTransacao, char *pValorTransacaoMaximo, char *pNumeroCupom);
	int TransacaoValor(char *pValorTransacao, char *pValorTransacaoMaximo, char *pNumeroCupom);
	int TransacaoCartaoCreditoConfirmada(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroCartao, char *pDataVencimento, char *pCVV2, char *pTipoOperacao, char *pNumeroParcelas, char *pValorTaxaServico, char *pMensagemTEF, char *pReservado);
	int TransacaoCancelamentoConfirmada(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTransacao, char *pNumeroControle, char *pNumeroCartao, char *pMensagemTEF, char *pReservado);
	int PreAutorizacaoCreditoConfirmada(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroCartao, char *pDataVencimento, char *pCVV2, char *pValorTaxaServico, char *pNumeroAutorizacao, char *pMensagemTEF, char *pReservado);
	int ConfPreAutorizacaoCreditoConfirmada(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pDataPreAutor, char *pNumeroCartao, char *pDataVencimento, char *pCVV2, char *pTipoOperacao, char *pNumeroParcelas, char *pMensagemTEF, char *pReservado);
	int TransacaoManualPOS (char *pValorTransacao);
	int TransacaoManualPOSCompleta (char *pValorTransacao, char *pCodigoEstabelecimento, char *pData, char *pHora, char *pNumeroAutorizadora, char *pNumeroCartao, char *pTipoOperacao, char *pNumeroParcelas, char *pDataPreDatado, char *pNumeroControle);
	int TransacaoCartaoFidelidade(char *pValorTransacao, char *pNumeroCupom, char *pCompraPontos, char *pQuantidadeItensTaxaVariavel, char *pItensTaxaVariavel, char *pNumeroControle);
	int TransacaoDebitoFidelidade(char *pNumeroCupom, char *pNumeroControle);
	int ConfirmaCartaoFidelidade(char *pNumeroControle);
	int ExtratoCartaoAutorizadorDirecao(char *pNumeroCartao, char *pNumeroControle);
	int RecebimentoAutorizadorDirecao(char *pValorTransacao, char *pNumeroCartao, char *pNumeroControle);
	int EstornoRecebimentoAutorizadorDirecao(char *pValorTransacao, char *pNumeroCartao, char *pNumeroControle);
	int RecebimentoCarneAutorizadorDirecao(char *pValorTransacao, char *pNumeroCartao, char *pDataVencimento, char *pNumeroControle);
	int TransacaoPagamentoConvenio(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int ConfirmaConvenio(char *pNumeroControle);
	int TransacaoSaqueRedecard(char *pValorTransacao, char *pNumeroCupomFiscal, char *pNumeroControle);
	int TransacaoSaque(char *pValorTransacao, char *pNumeroCupomFiscal, char *pNumeroControle);
	int TransacaoCDC1MIN(char *pValorTransacao, char *pNumeroCupomFiscal, char *pNumeroControle);
	int TransacaoSIMparcelado(char *pValorTransacao, char *pNumeroCupomFiscal, char *pNumeroControle);
	int TransacaoCartaoCreditoIATA(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoCartaoCreditoIATAConfirmada(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroCartao, char *pDataVencimento, char *pCVV2, char *pTipoOperacao, char *pNumeroParcelas, char *pValorTaxaServico,char *pValorEntrada, char *pMensagemTEF, char *pReservado);
	int TransacaoCartaoPrivateLabel(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	void BeepErro();
	int TransacaoConsultaSaldo(char *pNumeroCupom, char *pNumeroControle);
	int TransacaoConsultaSaldoCelular(char *pNumeroCupom, char *pNumeroControle);
	int TransacaoConsultaSaldoCompleta(char *pNumeroCupom, char *pNumeroControle, char *pTipoCartao, char *pPermiteAlteracao, char *pReservado);
	int ColetaCartaoDebito(char *pValorTransacao, char *pNumeroCupom, char *pParametrosTEF, char *pMensagemOperador);
	int ConsisteDadosCartaoDebito(char *pUltimosDigitos, char *pCodigoSeguranca, char *pMensagemOperador);
	int ColetaSenhaCartaoDebito(char *pNumeroControle, char *pMensagemOperador);
	int ConsultaParametrosPBM(char *pNumeroCupom, char *pQuantidadeRedes, char *pDadosRedes, char *pMensagemOperador);
	int ConsultaProdutosPBM(char *pNumeroCupom, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pAutorizacao, char *pDadosCRM, char *pTipoVenda, char *pValorTotalMedicamentos, char *pValorVista, char *pValorCartao, char *pCodigoCredenciado, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pReservado, char *pNumeroControle, char *pMensagemOperador);
	int TransacaoVendaPBM(char *pValorTotalMedicamentos, char *pNumeroCupom, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pAutorizacao, char *pNSUConsulta, char *pDadosCRM, char *pTipoVenda, char *pValorVista, char *pValorCartao, char *pCodigoCredenciado, char *pRegraNegocio, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pReservado, char *pNumeroControle, char *pNumeroControleRede, char *pMensagemOperador);
	int ConfirmaVendaPBM(char *pNumeroControle);
	int TransacaoReimpressaoVendaPBM();
	int TransacaoCancelamentoVendaPBM(char *pNumeroControle);
	int TransacaoCancelamentoPreAutorizacaoPBM(char *pNumeroControle);
	int TransacaoElegibilidadePBM(char *pNumeroCupom, char *pRedePBM, char *pMatricula, char *pDadosElegibilidade, char *pNumeroControle, char *pNumeroControleRede, char *pNomeCliente, char *pNomeMedico, char *pInformaDependente, char *pListaDependentes, char *pReservado, char *pMensagemOperador);
	int TransacaoPreAutorizacaoPBM(char *pNumeroCupom, char *pRedePBM, char *pAutorizacaoElegibilidade, char *pDadosFarmaceutico, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pNumeroControle, char *pNumeroControleRede, char *pReservado, char *pMensagemOperador);
	int TransacaoCancelamentoPreAutorizacaoPBM_TeleMarketing(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pMatricula, char *pReservado, char *pNumeroControle, char *pMensagemOperador);
	int TransacaoElegibilidadePBM_TeleMarketing(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroCupom, char *pRedePBM, char *pMatricula, char *pDadosElegibilidade, char *pNumeroControle, char *pNumeroControleRede, char *pNomeCliente, char *pNomeMedico, char *pInformaDependente, char *pListaDependentes, char *pReservado, char *pMensagemOperador);
	int TransacaoPreAutorizacaoPBM_TeleMarketing(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroCupom, char *pRedePBM, char *pAutorizacaoElegibilidade, char *pDadosFarmaceutico, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pNumeroControle, char *pNumeroControleRede, char *pReservado, char *pMensagemOperador);
	int ConsultaParametrosPBM_TeleMarketing(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroCupom, char *pQuantidadeRedes, char *pDadosRedes, char *pMensagemOperador);
	int ConsultaProdutosPBM_TeleMarketing(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroCupom, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pAutorizacao, char *pDadosCRM, char *pTipoVenda, char *pValorTotalMedicamentos, char *pValorVista, char *pValorCartao, char *pCodigoCredenciado, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pReservado, char *pNumeroControle, char *pMensagemOperador);
	int TransacaoVendaPBM_TeleMarketing(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pValorTotalMedicamentos, char *pNumeroCupom, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pAutorizacao, char *pNSUConsulta, char *pDadosCRM, char *pTipoVenda, char *pValorVista, char *pValorCartao, char *pCodigoCredenciado, char *pRegraNegocio, char *pQuantidadeMedicamentos, char *pMedicamentos, char *pReservado, char *pNumeroControle, char *pNumeroControleRede, char *pMensagemOperador);
	int TransacaoCancelamentoVendaPBM_TeleMarketing(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pReservado, char *pNumeroControle, char *pMensagemOperador);
	int TransacaoAberturaVendaPBM_TeleMarketing(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pReservado, char *pPedirDadosComplementares, char *pDadosComplementares, char *pInfoDadosComplementares, char *pMensagemOperador);
	int TransacaoVendaProdutoPBM_TeleMarketing(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pMedicamento, char *pReservado, char *pPedirDadosComplementares, char *pDadosComplementares,  char *pInfoDadosComplementares, char *pMensagemOperador);
	int TransacaoFechamentoVendaPBM_TeleMarketing(char *pNumeroEmpresa, char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pRedePBM, char *pTrilha1, char *pTrilha2, char *pDigitado, char *pConfirmacao, char *pReservado, char *pAutorizacao, char *pNumeroControle, char *pMensagemOperador);
	void InformaDadosMedicamentos(char *pIndicativoReceita, char *pRegistroProfissional, char *pListaMedicamentos);
	int TransacaoSaqueSaldo(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoSaqueExtrato(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoConsultaAVS(char *pNumeroControle);
	int TransacaoConsultaAVSConfirmada(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroCupom, char *pNumeroControle, char *pNumeroCartao, char *pDataVencimento, char *pCVV2, char *pEndereco, char *pNumero, char *pApto, char *pBloco, char *pCEP, char *pBairro, char *pCPF, char *pMensagemTEF, char *pReservado);
	int TransacaoPagamentoContasVisanet(char* pTipoConta, char *pCodigoBarras, char *pFormaPagamento, char *pTrilhaCartao, char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoEspecial(int iCodigoTransacao, char *pDados);
	int ConsultaValoresPrePago(char *pNumeroControle, char *pMensagemOperador);
	int TransacaoRecargaCelular(char *pCodigoArea, char *pNumeroTelefone, char *pNumeroControle);
	int ConsultaParametrosTeledata(char *pDadosTeledata, char *pMensagemOperador);
	int ConsultaChequesGarantidos(char *pTipoDocumento, char *pNumeroDocumento, char *pDataInicialConsulta, char *pDataFinalConsulta, char *pNumeroControle);
	int TransacaoSaqueCompleta(char *pValorTransacao, char *pNumeroCupomFiscal, char *pNumeroControle, char *pTipoTransacao, char *pPlanoPagamento, char *pNumeroParcelas, char *pPermiteAlteracao, char *pReservado);
	int TransacaoCartaoCompraSaque(char *pValorCompra,char *pValorSaque, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoCartaoCompraSaqueCompleta(char *pValorCompra,char *pValorSaque, char *pNumeroCupom,char *pNumeroControle,char *pPermiteAlteracao);
	int TesteRedeAtiva(char *pNumeroEmpresa, char *pNumeroLoja, char *pNumeroPDV, char *pCodigoRede, char *pStatusRede, char *pMensagemOperador);
	int TransacaoCadastraSenha(char *pNumeroControle);
	void ConfiguraFluxoExternoDTEF5();
	int TrataDesfazimento(int iTratar);
	int ConsultaTransacao(char *pNumeroEmpresa, char *pNumeroLoja, char *pNumeroPDV, char *pSolicitacao, char *pResposta, char *pMensagemErro);
	int TransacaoeValeGas(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroValeGas);
	int TransacaoConsultaeValeGas(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroValeGas, char *pDadosRetorno);
	int TransacaoCancelamentoPadrao(char *pNumeroControle);
	int ConfiguraModoTeleMarketing(int iModo);
	int ConfirmaCartaoTeleMarketing(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroControle, char *pMensagemTEF, char *pReservado);
	int DesfazCartaoTeleMarketing(char *pMultiLoja, char *pNumeroLoja, char *pNumeroPDV, char *pNumeroControle, char *pMensagemTEF, char *pReservado);
	int TransacaoEstatistica(char *pNumeroControle);
	int TransacaoInjecaoChaves(char *pNumeroControle);
	int TransacaoTrocoSurpresa(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pMensagemTEF, char *pReservado);
	int IdentificacaoAutomacaoComercial(char *pNomeAutomacao, char *pVersaoAutomacao, char *pReservado);
	int ConsultaTabelasValeGas(char *pNumeroControle, char *pMensagemOperador);
	int DefineBandeiraTransacao(char *pCodigoBandeira);
	int DefineRedeTransacao(char *pCodigoRede);
	int ConverteCodigoRede(char *pCodigoRede, char *pCodigoRedeDTEF5, char *pCodigoRedeDTEF8);
	int TransacaoAbreLote(char *pNumeroCupom, char *pNumeroControle, char *pMensagemTEF, char *pReservado);
	int TransacaoFechaLote(char *pNumeroCupom, char *pNumeroControle, char *pMensagemTEF, char *pReservado);
	void ConfiguraEmpresaLojaPDV(char *pNumeroEmpresa, char *pNumeroLoja, char *pNumeroPDV);
	int TransacaoResgatePremio(char *pNumeroCupom, char *pNumeroControle);
	int TransacaoVendaPOS(char *pCNPJ, char *pNumeroSerie, char *pCodigoFrentista, char *pCPFCNPJ, char *pPagamentoTEF, char *pCartaoProprio, char *pValor, char *pTelefoneCliente, char *pCodigoOrigem, char *pSaldoPontos, char *pCodigoPesquisa, char *pReservado, char *pNumeroControle);
	int TransacaoEstornoVendaPOS(char *pCNPJ, char *pNumeroSerie, char *pCodigoFrentista, char *pCPFCNPJ, char *pDataEstorno, char *pNSUEstorno, char *pAutorizacaoEstorno, char *pSaldoPontos, char *pNumeroControle);
	int TransacaoResgatePontosPOS(char *pCNPJ, char *pNumeroSerie, char *pCodigoFrentista, char *pCPFCNPJ, char *pQuantidadeProdutos, char *pListaProdutos, char *pSaldoPontos, char *pReservado, char *pNumeroControle);
	int TransacaoConsultaPontosPOS(char *pCNPJ, char *pNumeroSerie, char *pCodigoFrentista, char *pCPFCNPJ, char *pSaldoPontos, char *pReservado, char *pNumeroControle);
	int AtualizacaoFrentistasPOS(char *pCNPJ, char *pNumeroSerie, char *pNumeroFrentistas, char *pListaFrentistas, char *pReservado, char *pNumeroControle);
	int BuscaTabelaDTEF(int iTipoTabela, char *pNumeroControle);
	int TransacaoContratacao(char *pNumeroCupom, char *pNumeroControle);
	int TransacaoPrimeiraCompra(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoCadastro(char *pCNPJ, char *pNumeroSerie, char *pCodigoFrentista, char *pCPFCNPJ, char *pTelefoneCliente, char *pReservado, char *pNumeroControle);
	int TransacaoDesativacaoPOS(char *pCNPJ, char *pNumeroSerie, char *pNumeroSerieDesativacao, char *pFrentista, char *pNumeroControle);
	int TransacaoConsultaPOSAtivos(char *pCNPJ, char *pNumeroSerie, char *pNumeroPOSAtivos, char *pListaPOSAtivos, char *pNumeroControle);
	int ProcuraPinPad(char *pDados);
	int ApagaTabelasPinPad(char *pDados);
	int TransacaoFuncoesAdministrativas(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pReservado);
	int TransacaoQuitacaoCartaFrete(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoQuitacaoCartaFreteCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle,char *pNumeroCartaFrete,char *pQuantidadeChegada, char *pPermiteAlteracao, char *pReservado);
	int TransacaoCartaoCrediario(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoSimulacaoCrediario(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoPagamentoPrivateLabelCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pIndicadorDigitacao, char *pCodigoBarras, char *pNumeroCartao, char *pCodigoRede, char *pPermiteAlteracao, char *pReservado);
	int TransacaoCargaCartao(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoRecargaCartao(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int CadastraPDV();
	int CadastraPDVTelemarketing(char *pNumeroEmpresa, char *pNumeroLoja, char *pNumeroPDV, char *pMensagemTEF);
	int TransacaoCartaoCrediarioCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle, char *pNumeroParcelas, char *pDataParcela1, char *pValorParcela1, char *pValorEntrada, char *pPermiteAlteracao, char *pReservado);
	int TransacaoConsultaPlanos(char *pValorTransacao, char *pNumeroControle, char *pReservado, char *pPlanos);
	int ConsultaCadastroPDV(char *pMensagem);
	int ConsultaCadastroPDVTelemarketing(char *pNumeroEmpresa, char *pNumeroLoja, char *pNumeroPDV, char *pMensagemTEF);
	int TransacaoSimulacaoSaque(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle);
	int TransacaoBloqueioCartao(char *pNumeroCupom, char *pNumeroControle);
	int TransacaoDesbloqueioCartao(char *pNumeroCupom, char *pNumeroControle);
	int TransacaoConsultaCadastroCPFCompleta(char *pValorTransacao,char *pNumeroCupom, char *pNumeroControle,char *pTipoOperacao,char *pDocEmissor,char *pPermiteAlteracao,char *pReservado);
	int TransacaoDepositoCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle,char *pTipoOperacao,char *pDocEmissor,char *pDocDestinatario,char *pPermiteAlteracao,char *pReservado);
	int TransacaoSaqueDomesticoCompleta(char *pValorTransacao, char *pNumeroCupom, char *pNumeroControle,char *pTipoOperacao,char *pCodigoPIN,char *pDocDestinatario,char *pPermiteAlteracao, char *pReservado);
	int TransacaoAlteraSenhaUsuarioDTEF(char *pNumeroCupom, char *pNumeroControle);
	int DefineParametroTransacao(int iCodigoParametro, char *pValorParametro, int iTamanhoParametro);
	int DefineParametroConfirmacao(int iCodigoParametro,char *pValorParamtero,char *pTamanhoParametro);

	void setCallBackDisplayTerminal(ptrCallBackDisplayTerminal cbDisplayTerminal);
	void setCallBackDisplayErro(ptrCallBackDisplayErro cbCallBackDisplayErro);
	void setCallBackDisplayMensagem(ptrCallBackMensagem cbDisplayMensagem);
	void setCallBackBeep(ptrCallBackBeep cbBeep);
	void setCallBackSolicitaConfirmacao(ptrCallBackSolicitaConfirmacao cbSolicitaConfirmacao);
	void setCallBackEntraCartao(ptrCallBackEntraCartao cbEntraCartao);
	void setCallBackEntraDataValidade(ptrCallBackEntraDataValidade cbEntraDataValidade);
	void setCallBackEntraData(ptrCallBackEntraData cbEntraData);
	void setCallBackEntraCodigoSeguranca(ptrCallBackEntraCodigoSeguranca cbEntraCodigoSeguranca);
	void setCallBackSelecionaOpcao(ptrCallBackSelecionaOpcao cbSelecionaOpcao);
	void setCallBackEntraValor(ptrCallBackEntraValor cbEntraValor);
  void setCallBackEntraValorEspecial(ptrCallBackEntraValorEspecial cbEntraValorEspecial);
	void setCallBackEntraNumero(ptrCallBackEntraNumero cbEntraNumero);
	void setCallBackOperacaoCancelada(ptrCallBackOperacaoCancelada cbOperacaoCancelada);
	void setCallBackSetaOperacaoCancelada(ptrCallBackSetaOperacaoCancelada cbSetaOperacaoCancelada);
	void setCallBackProcessaMensagens(ptrCallBackProcessaMensagens cbProcessaMensagens);
	void setCallBackEntraString(ptrCallBackEntraString cbEntraString);
	void setCallBackConsultaAVS(ptrCallBackConsultaAVS cbConsultaAVS);
	void setCallBackMensagemAdicional(ptrCallBackMensagemAdicional cbMensagemAdicional);
  void setCallBackImagemAdicional(ptrCallBackImagemAdicional cbImagemAdicional);
	void setCallBackEntraCodigoBarras(ptrCallBackEntraCodigoBarras cbEntraCodigoBarras);
	void setCallBackEntraCodigoBarrasLido(ptrCallBackEntraCodigoBarrasLido cbEntraCodigoBarrasLido);
	void setCallBackMensagemAlerta(ptrCallBackMensagemAlerta cbMensagemAlerta);
	void setCallBackPreviewComprovante(ptrCallBackPreviewComprovante cbPreviewComprovante);
	void setCallBackSelecionaPlanos(ptrCallBackSelecionaPlanos cbSelecionaPlanos);
	void setCallBackSelecionaPlanosEx(ptrCallBackSelecionaPlanosEx cbSelecionaPlanosEx);

	void setTransacaoSemTelas();
	void ClasseIntegracao::RegistrarFuncoesCallBack();
	void descarregaDll();
  void recarregaDll(bool bOperacoesSemTelas);
	ClasseIntegracao(void);
	~ClasseIntegracao(void);
};

